spring:
  config:
    import: optional:file:${ENV_FILE:.env.oidc}[.properties]
  application:
    name: cloud-01-backend
  profiles:
    default: azure

---
spring:
  config:
    activate:
      on-profile: azure
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AZURE_ISSUER_URI}